spring:
  application:
    name: drex
  config:
    location: classpath:/*.properties
  r2dbc:
    url: r2dbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations:
      - classpath:/db/migration
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    installed-by: ${USER}
    validate-on-migrate: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics,prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles:
        http:
          - 0.5
          - 0.75
          - 0.99
          - 0.999